# Python Assignment
Topic: 3D Arrays and Dictionaries


# Part A – 3D Arrays  

# Question 1  
## Create the following 3D array.

Layer 1

[1, 2, 3]
[4, 5, 6]

Layer 2

[7, 8, 9]
[10, 11, 12]

In [ ]:
Write a Python program to:

Print the complete 3D array.
Print the first layer.
Print the second row of the second layer.
Print the element 11.

In [2]:
import numpy as np

# 1. Create the 3D array with Layer 1 and Layer 2
# Shape of the array is (2, 2, 3) -> 2 layers, 2 rows per layer, 3 elements per row
array_3d = np.array([
    [[1, 2, 3], 
     [4, 5, 6]],  
    
    [[7, 8, 9], 
    [10, 11, 12]
    ]
])

# 2. Print the complete 3D array
print("Complete 3D array:")
print(array_3d)
print("-" * 30)

# 3. Print the first layer (Index 0)
print("First layer:")
print(array_3d[0])
print("-" * 30)

# 4. Print the second row of the second layer (Layer Index 1, Row Index 1)
print("Second row of the second layer:")
print(array_3d[1, 1])
print("-" * 30)

# 5. Print the element 11 (Layer Index 1, Row Index 1, Column Index 1)
print("The element 11:")
print(array_3d[1, 1, 1])

Complete 3D array:
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
------------------------------
First layer:
[[1 2 3]
 [4 5 6]]
------------------------------
Second row of the second layer:
[10 11 12]
------------------------------
The element 11:
11


# Question 2  

Using the same 3D array, reverse the order of layers.

Expected Output

Layer 2

[7, 8, 9]
[10,11,12]

Layer 1

[1,2,3]
[4,5,6]

In [12]:

reversed_arr = arr[::-1]
layer_number = len(reversed_arr)
for layer in reversed_arr:
    print(f"Layer {layer_number}")
    for row in layer:
        print(row)
    print()  
    layer_number -= 1

Layer 2
[9, 8, 7]
[12, 11, 10]

Layer 1
[3, 2, 1]
[6, 5, 4]



# Question 3  

##  Reverse every row inside every layer.

Expected Output

In [8]:
for layer in arr:
    for row in layer:
        row.reverse()
layer_number = 1
for layer in arr:
    print(f"Layer {layer_number}")
    for row in layer:
        print(row)
    print()
    layer_number += 1

Layer 1
[3, 2, 1]
[6, 5, 4]

Layer 2
[9, 8, 7]
[12, 11, 10]



# Question 4  

Completely reverse the entire 3D array by reversing:

    the order of layers,
    the order of rows inside each layer,
    the elements inside every row.

Expected Output

[12,11,10]
[9,8,7]
[6,5,4]
[3,2,1]

In [14]:
arr = [
    [
        [1, 2, 3],
        [4, 5, 6]
    ],
    [
        [7, 8, 9],
        [10, 11, 12]
    ]
]
reversed_arr = [
    [row[::-1] for row in layer[::-1]]
    for layer in arr[::-1]
]

for layer in reversed_arr:
    for row in layer:
        print(row, end=" ")

[12, 11, 10] [9, 8, 7] [6, 5, 4] [3, 2, 1] 

# Part B – Dictionaries

In [ ]:
# Create a dictionary to store the following student details.

| Key        | Value   |
| ---------- | ------- |
| Roll No    | 101     |
| Name       | Alice   |
| Age        | 20      |
| Department | AI & DS |
| CGPA       | 8.9     |

Display all the information. (use print)

In [15]:
student = {
    "Roll No": 101,
    "Name": "Alice",
    "Age": 20,
    "Department": "AI & DS",
    "CGPA": 8.9
}
print("Roll No:", student["Roll No"])
print("Name:", student["Name"])
print("Age:", student["Age"])
print("Department:", student["Department"])
print("CGPA:", student["CGPA"])

Roll No: 101
Name: Alice
Age: 20
Department: AI & DS
CGPA: 8.9


In [ ]:
# Question 6  

Using the dictionary created above,

    Update the CGPA to 9.2
    Add a new key named City with value Chennai
    Display the updated dictionary.

In [16]:
student["CGPA"] = 9.2
student["City"] = "Chennai"
print(student)

{'Roll No': 101, 'Name': 'Alice', 'Age': 20, 'Department': 'AI & DS', 'CGPA': 9.2, 'City': 'Chennai'}


In [ ]:
# Question 7  

Write a program to print

    all keys
    all values
    all key-value pairs

using appropriate dictionary methods.

In [17]:
print("Keys:")
print(student.keys())
print("\nValues:")
print(student.values())
print("\nKey-Value Pairs:")
print(student.items())

Keys:
dict_keys(['Roll No', 'Name', 'Age', 'Department', 'CGPA', 'City'])

Values:
dict_values([101, 'Alice', 20, 'AI & DS', 9.2, 'Chennai'])

Key-Value Pairs:
dict_items([('Roll No', 101), ('Name', 'Alice'), ('Age', 20), ('Department', 'AI & DS'), ('CGPA', 9.2), ('City', 'Chennai')])


In [ ]:
# Question 8  

Create the following nested dictionary.

students = {
    "Student1": {
        "Name": "John",
        "Age": 22
    },
    "Student2": {
        "Name": "Alice",
        "Age": 21
    },
    "Student3": {
        "Name": "David",
        "Age": 20
    }
}

Write a program to

    Print the name of Student2.
    Print the age of Student3.
    Display all student names using a loop.

In [18]:
students = {
    "Student1": {
        "Name": "John",
        "Age": 22
    },
    "Student2": {
        "Name": "Alice",
        "Age": 21
    },
    "Student3": {
        "Name": "David",
        "Age": 20
    }
}


print("Name of Student2:", students["Student2"]["Name"])


print("Age of Student3:", students["Student3"]["Age"])


print("\nStudent Names:")
for student in students.values():
    print(student["Name"])

Name of Student2: Alice
Age of Student3: 20

Student Names:
John
Alice
David


In [ ]:
# Question 9  

Create a dictionary of five products.

Example

    Laptop
    Mouse
    Keyboard
    Monitor
    Printer

Each product should contain

    Product Name
    Price
    Quantity

Write a program to

    Display all products.
    Print the product with the highest price.
    Calculate the total inventory value

(Formula:  Inventory Value = Price × Quantity)

In [19]:
products = {
    "Laptop": {
        "Product Name": "Laptop",
        "Price": 50000,
        "Quantity": 10
    },
    "Mouse": {
        "Product Name": "Mouse",
        "Price": 500,
        "Quantity": 50
    },
    "Keyboard": {
        "Product Name": "Keyboard",
        "Price": 1200,
        "Quantity": 30
    },
    "Monitor": {
        "Product Name": "Monitor",
        "Price": 15000,
        "Quantity": 8
    },
    "Printer": {
        "Product Name": "Printer",
        "Price": 10000,
        "Quantity": 5
    }
}

for product, details in products.items():
    print(product)
    print("  Product Name:", details["Product Name"])
    print("  Price:", details["Price"])
    print("  Quantity:", details["Quantity"])
    print()

highest_price = 0
highest_product = ""

for product, details in products.items():
    if details["Price"] > highest_price:
        highest_price = details["Price"]
        highest_product = product
print(highest_product, "-", highest_price)
total_inventory = 0
for details in products.values():
    total_inventory += details["Price"] * details["Quantity"]

print("Total Inventory Value:", total_inventory)


Laptop
  Product Name: Laptop
  Price: 50000
  Quantity: 10

Mouse
  Product Name: Mouse
  Price: 500
  Quantity: 50

Keyboard
  Product Name: Keyboard
  Price: 1200
  Quantity: 30

Monitor
  Product Name: Monitor
  Price: 15000
  Quantity: 8

Printer
  Product Name: Printer
  Price: 10000
  Quantity: 5

Laptop - 50000
Total Inventory Value: 731000


In [ ]:
# Question 10

Create a dictionary of five students and their marks.

Example

    Alice : 85
    Bob : 92
    Charlie : 78
    David : 88
    Emma : 95

Write a Python program to

    Find the student with the highest marks.
    Find the student with the lowest marks.
    Calculate the average marks.
    Display students who scored more than 85.

In [20]:
# Create a dictionary of students and their marks
students = {
    "Alice": 85,
    "Bob": 92,
    "Charlie": 78,
    "David": 88,
    "Emma": 95
}

# 1. Find the student with the highest marks
highest_student = max(students, key=students.get)
print("Student with Highest Marks:")
print(highest_student, "-", students[highest_student])

# 2. Find the student with the lowest marks
lowest_student = min(students, key=students.get)
print("\nStudent with Lowest Marks:")
print(lowest_student, "-", students[lowest_student])

# 3. Calculate the average marks
average = sum(students.values()) / len(students)
print("\nAverage Marks:", average)

# 4. Display students who scored more than 85
print("\nStudents who scored more than 85:")
for student, marks in students.items():
    if marks > 85:
        print(student, "-", marks)

Student with Highest Marks:
Emma - 95

Student with Lowest Marks:
Charlie - 78

Average Marks: 87.6

Students who scored more than 85:
Bob - 92
David - 88
Emma - 95
